### ISSUE TITLE
General stats items missing (shots_fired, shots_hit, environmental_deaths)

### ISSUE THREAD

**Issue by dfreelan** [SunDwarf/OWAPI#193]
## Issue
some general stats items are missing since the patch 18 days ago.  I believe it worked on the patch before this

## Links that cause the issue
`https://owapi.net/api/v3/u/babybay-1469/blob`

I know the above link had stats for shots hit and shots fired before the last update (maybe 2 updates ago? last time i posted an issue this worked)

Others did as well but all seem to be missing now

**Comment by Js41637** [comment]
The api fetches data from the users Overwatch website stats, if something disappeared it would be because the data is no longer showing on the website. the website breaks frequently and it is currently partially broken and missing a lot of stats due to Doomfists release. Hopefully the site is updated soon but blizzard has a bad track record with keeping their site up to date and working

**Comment by dfreelan** [comment]
My bad! closing this issue--- clearly they got rid of it for now for whatever reason. Goddamnit blizzard!
