### ISSUE TITLE
Problem with avatar coming with the new event(halloween)

### ISSUE THREAD

**Issue by maxliguge** [SunDwarf/OWAPI#203]
Hi, just a simple note to let you know that new avatar that came with last update didn't get recognized by the api(Old avatar still works well though).

As an example, this user use one of the new avatar : https://owapi.net/api/v3/u/Mobi-2683/stats 

But his avatar return : 

https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x02500000000012D4.png 

Edit: Ok I've just realized that there is the same problem in OW forum. So I guess it's more an issue caused by blizzard itself.

**Comment by Js41637** [comment]
This is not an issue with the API, Halloween icons have not yet been added to the website. The urls are there but they haven't added the icons. This is because the urls are generated based on game data. That id for the icon is the ID of the icon in game. When I go to my profile on the website my avatar doesn't load.

**Comment by SunDwarf** [comment]
Great website.

Closing since this isn't an us issue.

**Comment by maxliguge** [comment]
Yeah thanks, we'll just wait like everyone else.
