### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by LawlyPopz** [SunDwarf/OWAPI#41]
just was trying to get stats and looks like your server is down :(

**Comment by SunDwarf** [comment]
Server is transitioning to being behind Cloudflare.

Some DNS servers aren't very happy about this. It'll be fixed Soon™.

**Comment by LawlyPopz** [comment]
[check out](http://api.lawlypopzz.xyz/overwatch/setup.php) this page I made for twitch bots using your api <3

**Comment by LawlyPopz** [comment]
@SunDwarf How long should this process take?

**Comment by SunDwarf** [comment]
I've reported the issue to Google DNS; OpenDNS and Level 3 both resolve it correctly.

**Comment by LawlyPopz** [comment]
I can load the page but i get this error 'Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR'

**Comment by drywolf** [comment]
I am also experiencing issues, but that might be related to this (maybe)

Since yesterday when I perform a player stats query, the query will have a repeating strange behavior for its response times.

Namely when I perform multiple queries to the same player profile my response times always look like this:

    Request 1: ~500ms
    Request 2: 20++ seconds
    Request 3: ~500ms
    Request 4: 20++ seconds
    Request 5: ~500ms
    Request 6: 20++ seconds

This only started happening since yesterday I guess, since before that the response times where roughly always consistent.

**Comment by SunDwarf** [comment]
How long is it between your requests @drywolf?

**Comment by Js41637** [comment]
I can get the response but it seems to be in a constant state of 'loading' at least when viewing via browser.

**Comment by SunDwarf** [comment]
This is technically known as a Blame Cloudflare™ issue.

It should be fine now, or at least after the DNS propogates again.

**Comment by drywolf** [comment]
@SunDwarf All the requests where done right after each other, but it all seems to be back to normal now and the responses are consistently in the ~500 ms range. :+1:

Thanks for looking into it.

**Comment by Js41637** [comment]
Seems to be returning fine for me now too.
