### ISSUE TITLE
Player level bug

### ISSUE THREAD

**Issue by chesterhow** [SunDwarf/OWAPI#68]
Player level received for players above level 100 seem to be only the last 2 digits.

E.g. Using this player `tape2#1581` who has a level of 275. Response received is `"level": 75,`

**Comment by Js41637** [comment]
If you want the full level you need to add the `rank` and `level` for all levels <100 you should get
```
"rank": 0,
"level: 72
```
and anything over will be
```
"rank": 1,
"level": 75
```
which is 175

**Comment by chesterhow** [comment]
Ah I see, so thats what the prestige is for. Thanks!

**Comment by Js41637** [comment]
I believe the reason they are separate because getting the prestige of a player is a lot more complex than getting the level, and there are cases where it us unable to correctly identify the prestige of a player in which it will return `undefined` or `null` (I think) instead of 0. So depending on how you use this and what language, you should check for 0 specifically.

**Comment by chesterhow** [comment]
Alright thanks for the heads up! I'll be sure to check for 0.

Also, I checked out the blizz website to see how the levels are displayed. Looks you guys did a ton of work! 👍🏼👍🏼
